<? if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5b9bafa10a548',
		'title' => 'Sections',
		'fields' => array(
			array(
				'key' => 'field_5b9bafde734b5',
				'label' => 'Blocks',
				'name' => 'blocks',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'5b9bb1c928ace' => array(
						'key' => '5b9bb1c928ace',
						'name' => 'text',
						'label' => 'Texte',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b9bb1e1734b7',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'title',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b9bb20c734b8',
								'label' => 'Texte',
								'name' => 'text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5ba4ae6586463',
								'label' => 'Asterisk',
								'name' => 'asterisk',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5ba61d4d70c54',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'bg-light' => 'Gris',
									'bg-primary' => 'Bleu',
									'bg-secondary' => 'Jaune',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'Blanc',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5ba612cd36480',
								'label' => 'Image de fond',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5b9bb2b0734ba' => array(
						'key' => 'layout_5b9bb2b0734ba',
						'name' => 'text_image',
						'label' => 'Texte et image',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b9bb2bc734bb',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5bd86d2a691ba',
								'label' => 'Section',
								'name' => 'section',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5bd86ddf691bb',
										'label' => 'Texte',
										'name' => 'text',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'full',
										'media_upload' => 1,
										'delay' => 0,
									),
									array(
										'key' => 'field_5bd86dfb691bc',
										'label' => 'Image',
										'name' => 'image',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ba4acdb8648b' => array(
						'key' => 'layout_5ba4acdb8648b',
						'name' => 'services',
						'label' => 'Services',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68c24d1ddd',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba4ad318648f',
								'label' => 'Service',
								'name' => 'service',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5ba4ae5d86490',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ba4ae6586491',
										'label' => 'Texte',
										'name' => 'text',
										'type' => 'textarea',
										'instructions' => 'Limité à 160 charactères',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => 160,
										'rows' => '',
										'new_lines' => '',
									),
									array(
										'key' => 'field_5ba62512a6789',
										'label' => 'Icon',
										'name' => 'icon',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'thumbnail',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ba4af1886493' => array(
						'key' => 'layout_5ba4af1886493',
						'name' => 'team',
						'label' => 'Équipe',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba61d2b70c62',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => 'Le titre affiché dans la section',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba61d4d70c63',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'Gris' => 'Gris',
									'Couleur' => 'Couleur',
									'Image' => 'Image',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'Blanc',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5ba61dba70c65',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ba61d4d70c63',
											'operator' => '==',
											'value' => 'Image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '1',
					),
					'layout_5ba630200ea4a' => array(
						'key' => 'layout_5ba630200ea4a',
						'name' => 'portfolio',
						'label' => 'Portfolio',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba630200ea4b',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => 'Le titre affiché dans la section',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba630200ea4c',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'Gris' => 'Gris',
									'Couleur' => 'Couleur',
									'Image' => 'Image',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Blanc',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5ba630200ea4e',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ba630200ea4c',
											'operator' => '==',
											'value' => 'Image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '1',
					),
					'layout_5ba630a0a7bfc' => array(
						'key' => 'layout_5ba630a0a7bfc',
						'name' => 'testimonials',
						'label' => 'Témoignages',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba630a0a7bfd',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => 'Le titre affiché dans la section',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba630a0a7bfe',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'Gris' => 'Gris',
									'Couleur' => 'Couleur',
									'Image' => 'Image',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'save_other_choice' => 0,
								'default_value' => 'Blanc',
								'layout' => 'horizontal',
								'return_format' => 'value',
							),
							array(
								'key' => 'field_5ba630a0a7c00',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ba630a0a7bfe',
											'operator' => '==',
											'value' => 'Image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '1',
					),
					'layout_5ba502470c6c0' => array(
						'key' => 'layout_5ba502470c6c0',
						'name' => 'price',
						'label' => 'Prix',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68c35d1dde',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b3eb37d734c2',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'Gris' => 'Gris',
									'Couleur' => 'Couleur',
									'Image' => 'Image',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'Gris',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5ba625cd54789',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5b9bb37d734c3',
											'operator' => '==',
											'value' => 'Image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5ba502550c6c1',
								'label' => 'Colonne',
								'name' => 'colonne',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'row',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5ba502770c6c2',
										'label' => 'Title',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ba502810c6c3',
										'label' => 'Prix',
										'name' => 'prix',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'min' => '',
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5ba502c60c6c4',
										'label' => 'Devise',
										'name' => 'devise',
										'type' => 'select',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'€' => '€',
											'$' => '$',
											'£' => '£',
											'¥' => '¥',
										),
										'default_value' => array(
											0 => '€',
										),
										'allow_null' => 0,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
									),
									array(
										'key' => 'field_5ba503630c6c5',
										'label' => 'Services',
										'name' => 'services',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'table',
										'button_label' => '',
										'sub_fields' => array(
											array(
												'key' => 'field_5ba5037b0c6c6',
												'label' => 'Texte',
												'name' => 'text',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
									array(
										'key' => 'field_5ba5040c0c6c7',
										'label' => 'Bouton',
										'name' => 'button',
										'type' => 'group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_5ba504470c6c8',
												'label' => 'Label',
												'name' => 'label',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ba504670c6c9',
												'label' => 'Lien',
												'name' => 'link',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array(
													'Interne' => 'Interne',
													'Externe' => 'Externe',
												),
												'allow_null' => 0,
												'other_choice' => 0,
												'default_value' => 'Externe',
												'layout' => 'vertical',
												'return_format' => 'value',
												'save_other_choice' => 0,
											),
											array(
												'key' => 'field_5ba6129e0c6ca',
												'label' => '',
												'name' => 'url',
												'type' => 'url',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array(
													array(
														array(
															'field' => 'field_5ba504670c6c9',
															'operator' => '==',
															'value' => 'Externe',
														),
													),
												),
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
											),
											array(
												'key' => 'field_5ba613070c6cb',
												'label' => '',
												'name' => 'int_url',
												'type' => 'page_link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array(
													array(
														array(
															'field' => 'field_5ba504670c6c9',
															'operator' => '==',
															'value' => 'Interne',
														),
													),
												),
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'post_type' => '',
												'taxonomy' => '',
												'allow_null' => 0,
												'allow_archives' => 1,
												'multiple' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '4',
					),
					'layout_5ba672c4eb0fd' => array(
						'key' => 'layout_5ba672c4eb0fd',
						'name' => 'carousel',
						'label' => 'Carousel',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68c56d1ddf',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba672ceeb0fe',
								'label' => 'Images',
								'name' => 'images',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'insert' => 'append',
								'library' => '',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5b86744c3c170' => array(
						'key' => 'layout_5b86744c3c170',
						'name' => 'stats',
						'label' => 'Statistiques',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b8c1b33b5cf8',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b86745a3c171',
								'label' => 'Jauges',
								'name' => 'radial_chart',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 1,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => 'Ajouter une jauge',
								'sub_fields' => array(
									array(
										'key' => 'field_5b8674b93c172',
										'label' => 'Opérateur',
										'name' => 'operateur',
										'type' => 'select',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'+' => '+',
											'-' => '-',
										),
										'default_value' => array(
											0 => '+',
										),
										'allow_null' => 1,
										'multiple' => 0,
										'ui' => 0,
										'return_format' => 'value',
										'ajax' => 0,
										'placeholder' => '',
									),
									array(
										'key' => 'field_5b86750f3c173',
										'label' => 'Pourcentage',
										'name' => 'percentage',
										'type' => 'number',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '%',
										'min' => 0,
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5b86b24d1b9fe',
										'label' => 'Label',
										'name' => 'label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '1',
					),
					'layout_5ba672f6eb0ff' => array(
						'key' => 'layout_5ba672f6eb0ff',
						'name' => 'gallery',
						'label' => 'Gallerie',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68c64d1de0',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba672f6eb100',
								'label' => 'Images',
								'name' => 'images',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'insert' => 'append',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5b9bb37d734bf' => array(
						'key' => 'layout_5b9bb37d734bf',
						'name' => 'link',
						'label' => 'Lien',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b9bb37d734c0',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'section-title',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5b9bb37d734c1',
								'label' => 'Texte',
								'name' => 'text',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5ba4ae6586493',
								'label' => 'Asterisk',
								'name' => 'asterisk',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'basic',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5b9bb3d9734c3',
								'label' => 'Bouton',
								'name' => 'button',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'table',
								'sub_fields' => array(
									array(
										'key' => 'field_5b9bb3f2734c4',
										'label' => 'Label',
										'name' => 'label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5b9bb404734c5',
										'label' => 'Lien',
										'name' => 'link',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Interne' => 'Interne',
											'Externe' => 'Externe',
										),
										'allow_null' => 1,
										'other_choice' => 0,
										'default_value' => 'Externe',
										'layout' => 'vertical',
										'return_format' => 'value',
										'save_other_choice' => 0,
									),
									array(
										'key' => 'field_5b9bb4a4734c6',
										'label' => '',
										'name' => 'url',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b9bb404734c5',
													'operator' => '==',
													'value' => 'Externe',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
									array(
										'key' => 'field_5b9bb4c7734c7',
										'label' => '',
										'name' => 'int_url',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5b9bb404734c5',
													'operator' => '==',
													'value' => 'Interne',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => '',
										'taxonomy' => '',
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
								),
							),
							array(
								'key' => 'field_5ba61d4d67c54',
								'label' => 'Fond',
								'name' => 'fond',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'Blanc' => 'Blanc',
									'bg-light' => 'Gris',
									'bg-primary' => 'Bleu',
									'bg-secondary' => 'Jaune',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'Blanc',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5ba612cd36489',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5b9bb37d564c3',
											'operator' => '==',
											'value' => 'Image',
										),
									),
								),
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ba6725ceb0fa' => array(
						'key' => 'layout_5ba6725ceb0fa',
						'name' => 'logos',
						'label' => 'Logos',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68b9426093',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba68a858e163',
								'label' => '',
								'name' => 'logo_list',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'min' => '',
								'max' => '',
								'insert' => 'append',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ba67318eb101' => array(
						'key' => 'layout_5ba67318eb101',
						'name' => 'contact',
						'label' => 'Contact',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ba68c6fd1de1',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ba6741fet102',
								'label' => 'Contact Form',
								'name' => 'contact_form',
								'type' => 'cf7',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'allow_null' => 0,
								'multiple' => 0,
								'disable' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5b86744c3c176' => array(
						'key' => 'layout_5b86744c3c176',
						'name' => 'faq',
						'label' => 'FAQ',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5b9bb37d214c0',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'section-title',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5bd7693a51484',
								'label' => 'FAQ',
								'name' => 'faq',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'table',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5bd7694d51485',
										'label' => 'Question',
										'name' => 'question',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5bd7695651486',
										'label' => 'Réponse',
										'name' => 'answer',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => '',
										'new_lines' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5b86744c3c477' => array(
						'key' => 'layout_5b86744c3c477',
						'name' => 'sets',
						'label' => 'Kits',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5c66b34f3b23e',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5c66b219dac9d',
								'label' => 'Tabs',
								'name' => 'tabs',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'row',
								'button_label' => '',
								'sub_fields' => array(
									array(
										'key' => 'field_5c66b254dac9e',
										'label' => 'Titre set',
										'name' => 'title_set',
										'type' => 'text',
										'instructions' => '',
										'required' => 1,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5c66b298dac9f',
										'label' => 'Prix du set',
										'name' => 'price_set',
										'type' => 'number',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '€',
										'min' => 0,
										'max' => '',
										'step' => '',
									),
									array(
										'key' => 'field_5cf7cb4d8ba32',
										'label' => 'Image',
										'name' => 'image-pack',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'url',
										'preview_size' => 'full',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5cf7cb708ba33',
										'label' => 'Notice photo',
										'name' => 'notice-photo',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5c66b2e5daca0',
										'label' => 'Texte set',
										'name' => 'text_set',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'media_upload' => 1,
										'toolbar' => 'full',
										'delay' => 0,
									),
									array(
										'key' => 'field_7ba5040c0c6c7',
										'label' => 'Bouton',
										'name' => 'button',
										'type' => 'group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_7ba504470c6c8',
												'label' => 'Label',
												'name' => 'label',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_7ba504670c6c9',
												'label' => 'Lien',
												'name' => 'link',
												'type' => 'radio',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'choices' => array(
													'Interne' => 'Interne',
													'Externe' => 'Externe',
												),
												'allow_null' => 0,
												'other_choice' => 0,
												'default_value' => 'Externe',
												'layout' => 'vertical',
												'return_format' => 'value',
												'save_other_choice' => 0,
											),
											array(
												'key' => 'field_7ba6129e0c6ca',
												'label' => '',
												'name' => 'url',
												'type' => 'url',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array(
													array(
														array(
															'field' => 'field_7ba504670c6c9',
															'operator' => '==',
															'value' => 'Externe',
														),
													),
												),
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'placeholder' => '',
											),
											array(
												'key' => 'field_7ba613070c6cb',
												'label' => '',
												'name' => 'int_url',
												'type' => 'page_link',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => array(
													array(
														array(
															'field' => 'field_7ba504670c6c9',
															'operator' => '==',
															'value' => 'Interne',
														),
													),
												),
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'post_type' => '',
												'taxonomy' => '',
												'allow_null' => 0,
												'allow_archives' => 1,
												'multiple' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5cf6db9f92e14' => array(
						'key' => 'layout_5cf6db9f92e14',
						'name' => 'concept',
						'label' => 'Concept',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5cf6e2b357ec9',
								'label' => 'Image',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5cf6dbb092e15',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5cf6dbc192e16',
								'label' => 'Description',
								'name' => 'description',
								'type' => 'textarea',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'maxlength' => '',
								'rows' => '',
								'new_lines' => '',
							),
							array(
								'key' => 'field_5cf6dbf11a5f4',
								'label' => 'Bouton',
								'name' => 'button',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5cf6dc381a5f5',
										'label' => 'Label',
										'name' => 'label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5cf6dc541a5f6',
										'label' => 'Lien',
										'name' => 'link',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'Interne' => 'Interne',
											'Externe' => 'Externe',
										),
										'allow_null' => 1,
										'other_choice' => 0,
										'default_value' => 'Externe',
										'layout' => 'vertical',
										'return_format' => 'value',
										'save_other_choice' => 0,
									),
									array(
										'key' => 'field_5cf6dcdd1a5f7',
										'label' => '',
										'name' => 'url',
										'type' => 'url',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5cf6dc541a5f6',
													'operator' => '==',
													'value' => 'Externe',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
									),
									array(
										'key' => 'field_5cf6dd171a5f8',
										'label' => '',
										'name' => 'int_url',
										'type' => 'page_link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5cf6dc541a5f6',
													'operator' => '==',
													'value' => 'Interne',
												),
											),
										),
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'post_type' => '',
										'taxonomy' => '',
										'allow_null' => 0,
										'allow_archives' => 1,
										'multiple' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5cf766d5d7371' => array(
						'key' => 'layout_5cf766d5d7371',
						'name' => 'promo',
						'label' => 'Promo',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5cf766e1d7372',
								'label' => 'Titre',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5cf7696f8efa3',
								'label' => 'Image',
								'name' => 'image_promo',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'url',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5cf766ebd7373',
								'label' => 'Introduction',
								'name' => 'introduction',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 1,
								'delay' => 0,
							),
							array(
								'key' => 'field_5cf7f217018cd',
								'label' => 'Notice',
								'name' => 'notice_intro',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5cf76838e530a',
								'label' => 'Formulaire',
								'name' => 'formulaire',
								'type' => 'cf7',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'allow_null' => 0,
								'multiple' => 0,
								'disable' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Ajouter une section',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/temp-blocks.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
			1 => 'excerpt',
			2 => 'discussion',
			3 => 'comments',
			4 => 'revisions',
			5 => 'slug',
			6 => 'author',
			7 => 'categories',
		),
		'active' => 1,
		'description' => '',
	));
	
	endif;